### ISSUE TITLE
Improve toHaveState's support for nested objects 

### ISSUE THREAD

**Issue by nickmccurdy** [FormidableLabs/enzyme-matchers#145]
1. If a component has an object key which is an object literal and you `expect(component).toHaveState('key', ...)` with another object literal (different references), the test will fail.
2. `[object Object]` strings are not very helpful for debugging.

![image](https://user-images.githubusercontent.com/927220/29419026-0110a9ec-833c-11e7-9a7b-81472e425116.png)

**Comment by blainekasten** [comment]
This is interesting. It's pretty common in React to avoid nested state values. Have you thought about flattening your state?

**Comment by nickmccurdy** [comment]
Good point. I guess this is kind of a weird use case, since I was actually using the result of `setState` to to test a utility function. I'm using Jest mocks now instead (which is cleaner in retrospect). I just found that behavior surprising.

**Comment by blainekasten** [comment]
Yeah. I would have expected it to print the object better. If you want to put in a PR to use the stringify module I'd be down.

**Comment by andreysaleba** [comment]
Hey, I've added PR to support nested objects

**Comment by mockdeep** [comment]
Just ran into the same issue with `.toHaveProps`.

**Comment by blainekasten** [comment]
@mockdeep what version are you on? @andreysaleba's fix should have applied globally.

**Comment by mockdeep** [comment]
Ah, okay, nevermind then. I'm on version `4.0.0` at the moment.

**Comment by blainekasten** [comment]
This has been fixed
