### ISSUE TITLE
.toBePresent() causes rendering of wrapped components in shallow mode

### ISSUE THREAD

**Issue by masterpi314** [FormidableLabs/enzyme-matchers#152]
Since it calls html(enzymeWrapper) even if it would pass otherwise, it causes failures if there's an error in the child component's render (or more likely even if you just passed mock props).  At the least it should not run this on pass, but it should probably do something other than html() for shallow renders.

https://github.com/blainekasten/enzyme-matchers/blob/7441cf5c6e4f2eb51b7f7b7fe9feef97fa7b8e9c/packages/enzyme-matchers/src/assertions/toBePresent.js#L19

**Comment by rtymchyk** [comment]
@masterpi314 it should be using Enzyme's `debug` for shallow rendered nodes, so it wouldn't do a full render: https://github.com/blainekasten/enzyme-matchers/blob/7441cf5c6e4f2eb51b7f7b7fe9feef97fa7b8e9c/packages/enzyme-matchers/src/utils/html.js#L48

**Comment by blainekasten** [comment]
@masterpi314 are you on latest? Can you make sure you are and confirm this? Maybe provide a minimal reproducible test?
