### ISSUE TITLE
[feature request] toHaveClass()

### ISSUE THREAD

**Issue by mikegleasonjr** [FormidableLabs/enzyme-matchers#153]
For me it is really rare to check that the `className` is exactly something. Plus, the order of the classes don't matter but can make a test fail if using `toHaveClassName()`.

`toHaveClass()` would just check if a `class` is in `className`.

EDIT: right now I'm using `expect(wrapper.hasClass('foo')).toBe(true);`

**Comment by blainekasten** [comment]
Hmm. Honestly, that's how I would have expected `.toHaveClassName()` to work.. I wouldn't think it has to be an exact match, but instead just that the component has that className at least.. I'd be open to a PR to fix this.

**Comment by franzheidl** [comment]
I use `expect(node.find('.myClass')).toBePresent();` which is _almost_ as explicit as `hasClass()`.

**Comment by mikegleasonjr** [comment]
@franzheidl Thanks for another solution but it does not convey the same meaning. I wanted to know if a specific element had a class... not if any element had a class.

**Comment by blainekasten** [comment]
@mikegleasonjr would you be willing to contribute a PR to add that matcher?

**Comment by mikegleasonjr** [comment]
@blainekasten I will try to do it today!

**Comment by blainekasten** [comment]
@mikegleasonjr I was just looking into this. And I'm fairly certain this is the existing behavior of `toHaveClassName`. Can you write up an example where this is not as expected? 

Specificially I'm looking at this test that is checking for one class on a node that has 2 classes.

https://github.com/FormidableLabs/enzyme-matchers/blob/master/packages/enzyme-matchers/src/assertions/__tests__/toHaveClassName--tests.js#L21

**Comment by blainekasten** [comment]
I'm going to close this. Let me know if it's still an issue and we can reopen it!
