### ISSUE TITLE
Automatically expose React, shallow, and mount on global

### ISSUE THREAD

**Issue by blainekasten** [FormidableLabs/enzyme-matchers#165]
I'm looking for community feedback on this idea. There is a lot of boilerplate to writing tests. Namely in that every one for jest and enzyme requires you to write something like this:

```
import React from 'react';
import { shallow, mount } from 'enzyme';
```

Why do we need to explicitly do that on every file?

I'm wondering if it would be smart for this library to inject them as globals much like it injects matchers in the global space.

cc @aaronabramov, @cpojer, @lelandrichardson

**Comment by cpojer** [comment]
You could have jest-environment-enzyme that inherits from the jsdom one and adds globals. That way it’s opt-in.

________________________________

**Comment by blainekasten** [comment]
@evocateur good call. I did it! `jest-environment-enzyme` and `eslint-config-jest-enzyme`

**Comment by evocateur** [comment]
@blainekasten Awesome, thanks!
