### ISSUE TITLE
Allow taking in an object for toHaveStyle

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [FormidableLabs/enzyme-matchers#171]
Given the following two assertions:

```javascript
expect(rendered).toHaveStyle("height", 7);
expect(rendered).toHaveStyle("overflowY", "hidden");
```

I'd like to test both at once with a partial match, like so:

```javascript
expect(rendered).toHaveStyle({
    height: 7,
    overflowY: "hidden"
});
```

**Comment by blainekasten** [comment]
> I'd like to test both at once with a partial match, like so:

When you say partial match. Are you saying, just one of them has to pass? I like the idea of supporting the object syntax. But I don't think it should only require partial match, I think it should require everything in the object to match.

Or are you saying it doesn't have to be a mirror of the elements entire style.

So for example this should pass even though display is omitted?

```
comp = <div style={{height: 7, overflowY: 'hidden', display: 'inline'}} />;
comp.toHaveStyle({height: 7, overflowY: 'hidden'}); 
```

**Comment by JoshuaKGoldberg** [comment]
> partial match
> entire style

What you said. I'm not very familiar with the Jasmine terminology 😄 but that's what I meant.

**Comment by blainekasten** [comment]
Ah cool. No worries! I like this idea! Would you want to put up a PR for this contribution?

**Comment by JoshuaKGoldberg** [comment]
Absolutely!

**Comment by blainekasten** [comment]
@JoshuaKGoldberg I took care of this one too. Expect a new major next week sometime!
