### ISSUE TITLE
Better error message for toBeEmpty when passed an improper input

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [FormidableLabs/enzyme-matchers#176]
```javascript
// TypeError: wrapper.getElements is not a function
expect([]).toBeEmpty();
```

It's confusing that the `toBeEmpty` assertion is exclusively for enzyme usage, and not regular arrays (as it is in other assertion libraries). The error message should reflect this.

**Comment by JoshuaKGoldberg** [comment]
Come to think of it, probably all matchers.

I would be up for submitting a PR... when I have time! No ETA on that just yet. :(

**Comment by blainekasten** [comment]
@JoshuaKGoldberg I'll be patient and wait for you to submit a PR! Thanks!

**Comment by blainekasten** [comment]
@JoshuaKGoldberg I had some time today and Implemented this. Thanks for raising it though!

**Comment by JoshuaKGoldberg** [comment]
Whoohoo!
