### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by wapgear** [FormidableLabs/enzyme-matchers#177]
What about typescript? Are you have plans to implement declaration for typescript, because now I cant use it with typescript, the compiler doesn't know about methods like `toHaveClassName` and shows errors.

**Comment by blainekasten** [comment]
@wapgear I don't personally use typescript so its hard for me to maintain that. I usually lean on the community to maintain that part. Are you using the `jasmine-matchers`? the `jest-matchers` do have [typescript defs](https://github.com/blainekasten/enzyme-matchers/blob/master/packages/jest-enzyme/src/index.d.ts)

We probably just need to port them over to the jasmine-matchers

**Comment by Lodin** [comment]
@wapgear, @blainekasten, `jasmine-matchers` has [typescript defs at DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jasmine-enzyme), so it can be installed with:
```bash
$ npm install @types/jasmine-matchers
```

**Comment by blainekasten** [comment]
Thanks for letting me know @Lodin. If you want, it might be nice to have that noted in the [README](https://github.com/FormidableLabs/enzyme-matchers/blob/master/packages/jasmine-enzyme/README.md)

**Comment by adrian-moisa** [comment]
The movement towards typescript is growing. I am using typescript + react. Unfortunately, I cannot trade-off typescript for flow. It is such a pity that I cannot use the enzyme matchers in my current environment. I bet that writing the type definitions will bring more people to this project.

**Comment by pascalduez** [comment]
@adrian-moisa As you can read in this thread there are indeed typings available, both in the definitely typed repo (maybe outdated) and in some of the packages here. Something's not working properly or missing?

**Comment by nulliel** [comment]
@adrian-moisa, @pascalduez, @blainekasten 

I just came across this issue. From my understanding TypeScript will only automatically import typings from `./node_modules/@types`. This means that the `./node_modules/jest-enzyme/lib/index.d.ts` will not be used automatically.

There are three remedies to this:

1. Update the `@types/jest-enzyme` package to point to up to the up-to-date definitions.
2. Add `import "jest-enzyme" to your test files.
3. Add the following `compilerOption` to your `tsconfig.json`:
```json
"typeRoots": ["./node_modules/@types", "./node_modules/jest-enzyme"]
```

Option #3 makes the most sense currently, but #1 is ideal.

**Comment by pascalduez** [comment]
> This means that the ./node_modules/jest-enzyme/lib/index.d.ts will not be used automatically.

Even with [`types: index.d.ts` in package.json](https://github.com/FormidableLabs/enzyme-matchers/blob/master/packages/jest-enzyme/package.json#L24) ?

I'm not a TS user so can't provide much assertion here.

**Comment by nulliel** [comment]
From my understanding the `types` key just states that the package has a typings file if it is not included in the root directory. 

Types are loaded when imported. `typeRoots` is used for auto loading types, which is useful for global or dynamically loaded modules.

**Comment by cyostephen** [comment]
@Lodin I think you've misunderstood. Defining `types` and `typeRoots` in `tsconfig.json` is for automatic inclusion of type files. By default this only points to the \@types folder, so all \@types files will be included.

When a project defines its own `types` key in its `package.json` it's saying "here are my types, but I'm a module so you'll need to include me". This is why the error goes away when you `include "jest-enzyme"`, and is why testing frameworks always expose their types through \@types/package.

**Comment by nulliel** [comment]
@Lodin I think you’ve misunderstood. Defining types and typeRoots in tsconfig.json is for automatic inclusion of type files. By default this only points to the @types folder, so all @types files will be included.

When a project defines its own types key in its package.json it’s saying “here are my types, but I’m a module so you’ll need to include me”. This is why the error goes away when you include “jest-enzyme”, and is why testing frameworks always expose their types through @types/package.

**Comment by Lodin** [comment]
@nulliel Oh I think I've got your position. I suppose you want to install `jest-enzyme` using setup file of Jest or someting like this, correct? I used `jest-enzyme` in [following way](https://github.com/Lodin/react-vtree/blob/master/__tests__/Tree.spec.tsx#L1) and didn't have any problems with typings. But I still think that option 3 from your post is better than publishing typings to the `@test`. It should be mentioned in README though.

**Comment by wsmd** [comment]
I have had a hard time figuring out how to get around the typescript compiler complaining about the `enzyme-matchers` methods not existing on the `Matchers` interface of Jest.

![screen shot 2018-07-08 at 12 06 51 am](https://user-images.githubusercontent.com/2100222/42416637-e41f0ea8-8242-11e8-8c0c-14e9ee757b14.png)


```
src/Head.spec.tsx:15:23 - error TS2339: Property 'toHaveText' does not exist on type 'Matchers<void>'.

15     expect(wrapper).toHaveText(message);
                       ~~~~~~~~~~
```

While adding ` import "jest-enzyme"` manually to your test files solves the problem, it can get very annoying in the long run!

I managed to get around this issue by adding a `global.d.ts` file at the root of my project with the following line:

```ts
// src/global.d.ts (doesn't have to be named "global", but it's just meaningful!)
import 'jest-enzyme';
```

All what this does is loading all the interface extensions provided by `jest-enzyme` and making them magically available in your typescript code!

Note that this file is only for global type definitions and is different from the one you will have to set up jest with (via `setupTestFrameworkScriptFile`; Jest still needs to know about the enzyme matchers).
