### ISSUE TITLE
Lint configuration missing

### ISSUE THREAD

**Issue by zwold** [FormidableLabs/enzyme-matchers#181]
I was setting up this project locally based on the Development section of the readme and discovered the lint command is not working. It looks like eslint-config-airbnb was removed from package.json in fbea1c9. When I add this back in, it runs but finds 4 errors. Is adding this config back the desired approach? If so, ok if I look into fixing the errors, too?

**Comment by blainekasten** [comment]
@zwold good find! That looks to be a mistake. I would say you're right on point. That'd be great if you could fix the errors and add the config

**Comment by blainekasten** [comment]
This was fixed!
