### ISSUE TITLE
4.0.2 breaks compatibility with 4.0.1 - removing properties with {undefined} value

### ISSUE THREAD

**Issue by fvicente** [FormidableLabs/enzyme-matchers#184]
My package.json is using jest-enzyme: "^4.0.1", and my jest snapshots where created and committed with version 4.0.1
In another environment, I made an npm install, and because of the ^ in front of the version, it installed 4.0.2 - the problem is that the same test won't pass, because this new version excludes properties with {undefined} value.

Should not a breaking change like this one increase the major version of the library instead of the patch number? (specially because snapshots between the same major/minor seems to be incompatible between 4.0.1 and 4.0.2)
Or is it just my problem and I just need to stop using ^ on the version and fix it to a specific number?

**Comment by blainekasten** [comment]
You are definitely right in assuming a patch change should not break your tests.

Though I am lost on what is excluding undefined properties. Do you have any idea what change caused that?

**Comment by fvicente** [comment]
Yeh, I'm looking at the commits on this project and I don't understand either. Maybe the fact of bumping enzyme-to-json from 3.0.0 to 3.3.0 ([this commit](https://github.com/blainekasten/enzyme-matchers/commit/0d8fefa3c2d89b41e3be0fa8e5f45e17feb8e876)) caused the snapshot to be generated differently.

I can try to make a minimal test case, but basically what I saw in my environment is that if you have `<Comp a={1} b={undefined} />` the generated snapshot in the newer version looks like this `<Comp a={1} />`. Maybe [this](https://github.com/adriantoine/enzyme-to-json/issues/21) bug?

Anyway, I think that you can close this issue as it doesn't seem to be directly related to your project, and the solution is simply update to the latest version and regenerate the snapshots.

**Comment by blainekasten** [comment]
I'm going to close because this hasn't came up by other people. Sorry about any unexpected problems! If this comes up for anyone else, please raise an issue or comment here!
