### ISSUE TITLE
toMatchElement not respecting Arrays

### ISSUE THREAD

**Issue by vitreuz** [FormidableLabs/enzyme-matchers#186]
It seems that [as per the documentation](https://github.com/blainekasten/enzyme-matchers#tomatchelementreactinstanceobject) toMatchElement is meant to match on props, however when the prop is an array it ignores the content.

Ex:
```jsx
it("renders 5 0's", () => {
  const wrapper = shallow(<MyComponent />)

  expect(wrapper).toMatchElement(<MyRow row={[0, 0, 0, 0]} />)
);
```
This would successfully match on:

```jsx 
<MyRow row={["some", "random", "values"]} />
```

**Comment by blainekasten** [comment]
So, the logic for matching element is actually really simple. It just runs enzyme's `debug()` method and compares the strings. 

I did a test and enzyme masks objects and arrays. This is unexpected, I thought it used to work..

Either way, I've got a ticket going with Enzyme to see where the fix lies: https://github.com/airbnb/enzyme/issues/1476

**Comment by blainekasten** [comment]
I put up a PR in enzyme for this. So hopefully this will get fixed
