### ISSUE TITLE
toHaveStyle for React-Native

### ISSUE THREAD

**Issue by dennis-tra** [FormidableLabs/enzyme-matchers#190]
Hey there,

I started using enzyme-matchers with `react-native` + `styled-components` recently. In `react-native` you can set the `style` prop to an array of objects instead of having just a single `style` object.  From the docs:
> The `style` prop can be a plain old JavaScript object. That's the simplest and what we usually use for example code. You can also pass an array of styles - the last style in the array has precedence, so you can use this to inherit styles.

Since an array of styles is not handled by the `toHaveStyle` assertion and `styled-components` is (apparently) defining an array of styles by default I can't get any test using this assertion to pass. So my first question is: Is `enzyme-matchers` made for also being used with react native? If so, I'm happy to file a PR which adds the handling of arrays to the `toHaveStyle` assertion.

At the moment I'm using a custom assertion by expanding `expect`:
```javascript
expect.extend({
  toHaveStyle(enzymeWrapper, styleKey, styleValue?) {
    const style = enzymeWrapper.prop("style");

    if (!style) {
      return {
        pass: false,
        message: () => `Expected a style prop but it did not find one.`,
        negatedMessage: () => `Expected not to find a style prop but it did.`,
      };
    }

    let pass = false;

    if (style instanceof Array) {
      const foundStyle = style
        .filter(s => s && Object.prototype.hasOwnProperty.call(s, styleKey))
        .reduce((a, c) => c[styleKey] || a, undefined);

      pass = this.equals(foundStyle, styleValue);
    } else if (!Object.prototype.hasOwnProperty.call(style, styleKey)) {
      return {
        pass: false,
        message: () => `Expected to find a style key of "${styleKey}".`,
        negatedMessage: () => `Expected to find a style key of "${styleKey}".`,
      };
    } else {
      pass = this.equals(style[styleKey], styleValue);
    }

    return {
      pass,
      message: () =>
        `Expected component style values to match for key "${styleKey}", but they didn't`,
      negatedMessage: () =>
        `Expected component style values to be different for key "${styleKey}", but they weren't`,
    };
  },
});
```

This is a mostly the assertion from this library extended by the `if (style instanceof Array)` case.

Cheers,
Dennis

**Comment by blainekasten** [comment]
I would expect this library to work with `react-native`. Definitely would appreciate a PR if you could do it!

**Comment by finnigantime** [comment]
Yes, we had success using this library with a custom react renderer based off of react-native renderer.

**Comment by dennis-tra** [comment]
@blainekasten alright. I'll hand in my PR over the weekend ;)
