### ISSUE TITLE
[jest-enzyme] Is there a matcher that verifies presence of exactly one component, given its name as string?

### ISSUE THREAD

**Issue by nbkhope** [FormidableLabs/enzyme-matchers#200]
Using `.toBePresent()` makes sure at least one component exists. However, is there a specific matcher to check if exactly one is present, given its display name? As an example:

```
// without jest-enzyme
expect(wrapper.find('div').length).toBe(1);

// any equivalent?
expect(wrapper.find('div')).toBePresentOnlyOne();
```

I also looked into `toContainReact()`, but using it requires me importing the component and using it instead of just using its display name as a string.

**Comment by blainekasten** [comment]
@nbkhope There isn't anything right now. I'm trying to think through this a bit more abstractly to see if there is a smart solution... I don't like the idea of creating a method that specifically checks for 1. And I'm not sure if it's common enough to check the literal length enough to warrant it.

It's not a hard add, but it feels a bit unnecassary. How often do you find yourself asserting an exact length?

**Comment by blainekasten** [comment]
closing due to unresponsiveness for now. Feel free to respond and start the discussion more and we can reopen if necassary.
