### ISSUE TITLE
Contradicting test fail report for toHaveText jasmine

### ISSUE THREAD

**Issue by Xesenix** [FormidableLabs/enzyme-matchers#201]
I'm running this test:
```
expect(component.find('strong')).toHaveText('REACT is working');
```
on this component:
```
<div className="box">
  <strong>REACT is working xxx</strong>
</div>
```
end getting this error report:
```
Expected <strong> components text to match (using ===), but it did not.
expected: Actual HTML: "REACT is working xxx"
received: Expected HTML: "REACT is working"
```
Lines 2 and 3 have contradicting content i would expect something like this:
```
Expected <strong> components text to match (using ===), but it did not.
Actual received HTML: "REACT is working xxx"
Expected HTML: "REACT is working"
```

**Comment by blainekasten** [comment]
ha, yeah that's dumb. Probably an easy fix. I'll look into it.

**Comment by Xesenix** [comment]
@blainekasten I have made some fast check but couldn't find right hook point to run it instead of current, but im beginner at writing webpack plugins so maybe you will have more luck.

**Comment by blainekasten** [comment]
@Xesenix what version are you on? I just tested this and didn't get a failure. It passed with the same component and assertion
