### ISSUE TITLE
toExist() gone?

### ISSUE THREAD

**Issue by tristan-shelton** [FormidableLabs/enzyme-matchers#207]
I just installed `jest-enzyme@4.2.0`, followed the setup instructions and tried to write a simple test: `expect(wrapper.find('button')).toExist()` which failed claiming that `expect(...).toExist is not a function`. Naturally I assumed I had set it up incorrectly, but after spending the better part of an hour trying to figure out why I finally checked what `matchers` actually was in `jest-enzyme/lib/index.js` and this is the result I got:

```
{
      toBeChecked: [Function],
      toBeDisabled: [Function],
      toBeEmpty: [Function],
      toBePresent: [Function],
      toContainReact: [Function],
      toHaveClassName: [Function],
      toHaveHTML: [Function],
      toHaveProp: [Function],
      toHaveRef: [Function],
      toHaveState: [Function],
      toHaveStyle: [Function],
      toHaveTagName: [Function],
      toHaveText: [Function],
      toIncludeText: [Function],
      toHaveValue: [Function],
      toMatchSelector: [Function],
      toMatchElement: [Function]
}
```

I changed `toExist()` to `toBePresent()` and my test passed. As far as I can tell `jest-enzyme` just maps the matchers in `enzyme-matchers` so I assume the main readme should be updated to reflect the change in API?

**Comment by SimenB** [comment]
See https://github.com/FormidableLabs/enzyme-matchers/pull/205

**Comment by blainekasten** [comment]
@tristan-shelton Hey! Sorry bad timing. Master isn't the latest published yet. I'm preparing a 5.0 release in the next few days. This is the docs for the latest publish https://github.com/FormidableLabs/enzyme-matchers/commit/a61e606ff72b41ac7163615575c3bcee321bda96

**Comment by tristan-shelton** [comment]
Ah! Good to know. Thanks for the clarification!
