### ISSUE TITLE
[jasmine-enzymye]: Matcher calls generate runtime errors in Typescript project

### ISSUE THREAD

**Issue by medington** [FormidableLabs/enzyme-matchers#222]
# Description
After installing the `jasmine-enzyme` module and `@types/jasmine-enzyme` into an existing 
project using Karma I'm running in to the following error when the tests are run:

![image](https://user-images.githubusercontent.com/2753206/37170351-77bf0bce-22bf-11e8-80a0-c20b753914ad.png)

Here is the stack in Chrome Dev Tools:

![image](https://user-images.githubusercontent.com/2753206/37170493-ce37b096-22bf-11e8-88a9-3e8e6cf450ee.png)

# Steps to reproduce
1. git clone -b failure https://github.com/medington/jasmine-enzyme-ts.git
2. cd jasmine-enzyme-ts 
3. npm install
4. npm run test

# Additional Notes
* That is a bare bones project with just the test module and what is needed to run it installed.
* The git sha at the `failure` tag (see step) 1 will reproduce the problem, it's fixed on master HEAD (see comments below)

```
create-react-app react-enzyme-test --scripts-version=react-scripts-ts
```

I've tried to narrow down what is different between that project and this one but no luck so far.

**Comment by medington** [comment]
This may not be related, but when I setup the project I was initially getting an error on an import statement in the test when using the  the default `tsconfig.json` with the `"esModuleInterop": true ` option enabled.

```import * as Adapter from "enzyme-adapter-react-16";```

searching on that error led me to this Typescript issue: [--esModuleInterop changes meaning of declaration](https://github.com/Microsoft/TypeScript/issues/21535). When I changed the import to instead be:

```
import Adapter = require("enzyme-adapter-react-16");
```
That changed the error to be a little different:

![image](https://user-images.githubusercontent.com/2753206/37172660-4a943f82-22c6-11e8-9b1d-bb1d41338b27.png)

Again, probably not related, but the esModuleInterop option is one of the defaults when using ```tsc init``` to initialize a new config file.

**Comment by blainekasten** [comment]
That error in the last comment means you tried to pass a not-enzyme object to an enzyme-matcher assertion.

Something like `expect({foo: 'bar'}).toHaveState('foo', 'bar)` would throw an error like that. What is happening  in your `src/index.spec.tsx:57` ?

**Comment by medington** [comment]
Hi @blainekasten thanks for the message. There is no line 57 in the file, I believe that's number corresponds to a file output by webpack. The test is as simple as I could make it, the file is:

https://github.com/medington/jasmine-enzyme-ts/blob/master/src/index.spec.tsx

It's the original issue I'm more concerned with getting resolved though. That one prevents me from using the enzyme matchers with typescript.

**Comment by blainekasten** [comment]
@medington I'll try to be as helpful as I can but I don't use jasmine or ts in my day job. Does this comment and export give you any guidance?

https://github.com/FormidableLabs/enzyme-matchers/blob/master/packages/jasmine-enzyme/src/index.js#L74-L80

**Comment by ryan-roemer** [comment]
@medington -- I cloned your repo and straight up `master` works on my machine with:

```
  Jasmine/Enzyme Sanity Tests
    ✓ says hello via mount with matcher
    ✓ says hello via renderIntoDocument
    ✓ says hello via mount

Chrome 64.0.3282 (Mac OS X 10.12.6): Executed 3 of 3 SUCCESS (0.039 secs / 0 secs)
TOTAL: 3 SUCCESS
```

I made this modification because I think it's closer to what you want:

```diff
diff --git a/src/index.spec.tsx b/src/index.spec.tsx
index 9b7b86a..a2f3247 100644
--- a/src/index.spec.tsx
+++ b/src/index.spec.tsx
@@ -4,7 +4,7 @@ import * as TestUtils from "react-dom/test-utils";
 import * as Enzyme from "enzyme";
 // See the note in the tsconfig.json file about this import
 // import * as Adapter from "enzyme-adapter-react-16";
-import Adapter = require("enzyme-adapter-react-16");
+import {default as Adapter} from "enzyme-adapter-react-16";
 import jasmineEnzyme from "jasmine-enzyme";
 
 Enzyme.configure({ adapter: new Adapter() });
```

And that also passes.

Also, side note -- is `"cheap-module-eval-source-map"` recommended in Karma tests? Source maps are notoriously fickle, and that one in particular seems weird to place in a test because _real code_ doesn't go in your test, instead a bug `eval(REAL_CODE_AS_STIRNG)` is outputted IIRC.

Hope that helps!

**Comment by medington** [comment]
@blainekasten Thanks. I got my test to work. Your tip about the error led me back to play with it some more and as I suspected, the way the adapter is being imported is a factor in the original error message I was seeing. Your tip about the 2nd error I posted was because my code was incorrect:

```
  it('says hello via mount with matcher', () => {	   it('says hello via mount with matcher', () => {
     jasmineEnzyme();	     jasmineEnzyme();
     const hello = Enzyme.mount(<Hello/>);	     const hello = Enzyme.mount(<Hello/>);
    expect(hello.text()).toHaveText('hello');	+    expect(hello).toHaveText('hello');
   });
```

The last line should have been just `expect(hello)` and not `expect(hello.text())`. However I wasn't seeing that error initially as the "TypeError: jasmine_enzyme_1.default is not a function" function error was preventing that call from ever being made.

For anyone else following this, I pushed updates to my test project here with comments:

https://github.com/medington/jasmine-enzyme-ts/commit/42d88664211764e5dfbef5ce3ad3a28ee2c55f9f

At this point my feeling is that the documentation here:

https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md

Needs to either be updated or include a note regarding the way the adapter is imported when using Typescript the documentation I pointed at in my earlier message. Should I log an issue with the project?

**Comment by ryan-roemer** [comment]
@medington -- actually, I just tried:

```js
import Adapter from "enzyme-adapter-react-16";
```

and that worked fine too. Are there any problems import-wise still on your end, or just with the assertions/substantive code at this point?

**Comment by medington** [comment]
Hi @ryan-roemer - Thank you very much for looking into this issue!

> @medington -- I cloned your repo and straight up master works on my machine with:

That's because I had just pushed changes to fix it. If you checkout the "failure" tag or clone that directly it will fail (I updated my steps to reproduce to indicate this).

Just reverting the import to:

```import Adapter from "enzyme-adapter-react-16";```

at the head of master will also work because the tsconfig.json entry is in there:

```"esModuleInterop": true,```

If you comment that out and try again you should see the error. Better yet, checkout the "failure" tag.

> Also, side note -- is "cheap-module-eval-source-map" recommended in Karma tests? Source maps are notoriously fickle, and that one in particular seems weird to place in a test because real code doesn't go in your test, instead a bug eval(REAL_CODE_AS_STIRNG) is outputted IIRC.

Tell me about it. I've struggled mightily with different source type maps. I've experimented with most all of the different types haven't found any type that works as well with unit tests as I would like. I think that one works when I debug a unit test in Chrome Dev Tools but if you can suggest a better setting to use I'd love to hear it!

**I'm still thinking that there needs to be some sort of documentation change made regarding the adapter import syntax.** If you read the [Typescript Module Docs](https://www.typescriptlang.org/docs/handbook/modules.html) it states:

>When importing a module using export =, TypeScript-specific import module = require("module") must be used to import the module.

For reference, the react 16 adapter index.d.ts contains this:

```
// Type definitions for enzyme-adapter-react-16 1.0
// Project: https://github.com/airbnb/enzyme
// Definitions by: Tanguy Krotoff <https://github.com/tkrotoff>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.6

import { EnzymeAdapter } from 'enzyme';

declare class ReactSixteenAdapter extends EnzymeAdapter {
}

declare namespace ReactSixteenAdapter {
}

export = ReactSixteenAdapter;
```

**Comment by medington** [comment]
This issue should probably be closed. If there is any change to be made it's to the documentation for the Jasmine enzyme docs.
