### ISSUE TITLE
Documentation needs to change after recent commit

### ISSUE THREAD

**Issue by tonyhallett** [FormidableLabs/enzyme-matchers#227]
[jest-environment-enzyme readme](https://github.com/FormidableLabs/enzyme-matchers/tree/master/packages/jest-environment-enzyme#readme) states that 'With this library, you don't need to have your app install enzyme, or an enzyme-adapter.  We'll take care of it for you! ".  This [commit](https://github.com/FormidableLabs/enzyme-matchers/commit/10bfa16d488a24a9dd28472e308fd37b5ddcb332) has removed all enzyme adapter dependencies.

**Comment by blainekasten** [comment]
Ah yeah. 6.0.0 changed that and I forgot about the docs. Do you want to submit a PR to update that?

**Comment by tonyhallett** [comment]
@blainekasten Apologies but I am really busy at the moment so it might be a while before I do it.  Probably best if you assign it to someone.
