### ISSUE TITLE
Forked jasmine fixture filename typo (Is it old copy?).

### ISSUE THREAD

**Issue by Jamamuuga** [FormidableLabs/enzyme-matchers#233]
In packages/jasmine-enzyme/spec/fixtures There is both a "toHaveState.fixture.js" and a "toHaveState.fixture.". The latter has a truncated filename & cloning the repo with git cli on git bash on windows (not windows subsystem for linux) or github desktop, gets the final dot truncated from the filename. Trying to clone the repo with gitkraken on windows gives an error. The proper file seems to be newer & has the same style and last commit date as most of the other fixtures. The odd file is 14 months older & has a different style. The odd file's contents seem to match the filename so it is probably just either just a copy of an old version of the proper one & something happened to it. If the proper one doesn't need anything from it, the odd file could probably just be deleted.

**Comment by blainekasten** [comment]
Sounds like a nice cleanup! Are you interested in doing this for us?
