### ISSUE TITLE
Improve Getting Started Documentation

### ISSUE THREAD

**Issue by xml** [FormidableLabs/enzyme-matchers#236]
Hi! First, many thanks for Formidable for providing such an amazing suite of tools for Jest and Enzyme!

There are 5 different sub-packages contained within this main repo. But, usage pattern is very unclear. In fact, this repo has no installation instructions at all, and no link to a docs website.

- How should I ideally install them? Just using this main monorepo? 
  - That's what it implies in the README for the `enzyme-matchers` sub-package, but not here: _"This package is primarily meant to be consumed by framework integrations within this monorepo."_ Er?
  - If so, how best to do that? Use npm to install the various components? But when I visit the readme's for the various packages, they're pretty silent on the how and why...
- jest-environment-enzyme says it's seemingly designed to pull in other tools. Is it all of these? Some of them? Others entirely?
- What are the dependencies between these 5? 
- Can I install one and get them all, or are they totally separate? 
- If they're totally separate: 
  - shouldn't the enzyme-matchers API be documented on that sub-component rather than here?
  - And how to I use all the others? Do they just provide globals? What consumes those globals? Why do I actually need them?

**Comment by blainekasten** [comment]
@xml that raises a really good point. We recently wrote a [blog post](http://formidable.com/blog/2018/assertions-and-testing-with-enzyme-matchers-6/) on it, but that's not the most helpful when you come here. 

I'm going to mark this ticket as a TODO to improve our readme's because it is pretty unhelpful, I agree.

**Comment by blainekasten** [comment]
Did you want direct answers to your questions now to help you move forward? That blog might help clarify some things.

**Comment by xml** [comment]
Well, I read that blog post, and for now, I INSTALLED ALL THE THINGS. :-) But, I still can't say I still feel confident that I understand them all.

**Comment by blainekasten** [comment]
Fixed by #279
