### ISSUE TITLE
Ignore whitespaces between tags by toHaveHTML

### ISSUE THREAD

**Issue by astorije** [FormidableLabs/enzyme-matchers#246]
At the moment, one has to write:

```js
expect(component).toHaveHTML('<div class="row"><div class="col-1"><div class="tile"><div class="label">Label line</div><div class="content">Value line</div><div class="footnote">Footnote line</div></div></div></div>');
```

It would be really nice if this could be expanded in a more readable form and let the assertion ignore the blanks between tags:

```js
expect(component).toHaveHTML(
  `<div class="row">
    <div class="col-1">
      <div class="tile">
        <div class="label">Label line</div>
        <div class="content">Value line</div>
        <div class="footnote">Footnote line</div>
      </div>
    </div>
  </div>`
);
```

I have this change locally and it works well, haven't noticed any downsides so far, so happy to turn it into a PR if you are open to that.

(I cannot use something like:
```js
expect(component).toHaveHTML(
  '<div class="row">' +
    '<div class="col-1">' +
      /* ... */
```
because automated formatters such as [Prettier](https://prettier.io/) reformat this accordingly.)

**Comment by blainekasten** [comment]
I think this would be a great addition! Would love to see the PR

**Comment by astorije** [comment]
Awesome, thanks @blainekasten, I did this in #250!
