### ISSUE TITLE
Why Use jest-environment-enzyme?

### ISSUE THREAD

**Issue by machineghost** [FormidableLabs/enzyme-matchers#248]
The jest-environment-enzyme readme explains how to install the module, but not *why* anyone would want to.  I found https://github.com/FormidableLabs/enzyme-matchers/pull/208, which provides the following:

>Never manually configure Enzyme adapters again!
>Never import React or enzyme in your tests. They are global!

But out of context that doesn't make a lot of sense.  Ok, I don't have to configure my Enzyme adapter ... except I still do inside the `jest-environment-enzyme` config, so the module hasn't eliminated any configuration, it just moved it to a new place.  As for the second feature, anyone who wants can write `global.React = React`.

So surely the whole point of the module isn't to save you from writing your own one-line global statement and create a new (but otherwise useless) place to configure your adapter.  Surely it does ... something useful?  But since someone new to the library has no idea what that something useful is, it'd be nice if the readme spelled it out.

**Comment by blainekasten** [comment]
If you don't find it useful, that's cool. If you want to improve the docs, that'd be cooler. Would love a PR. Probably would have taken about the same amount of time this issue took.

**Comment by machineghost** [comment]
How can I improve the docs if I don't know the answer to the question?  You know the reason why your library is useful: the entire point of the ticket was that I don't.

**Comment by brneto** [comment]
@machineghost, I used to write into my global, imports like `@babel/polyfill` together with the configuration of  Enzyme adapters. Using this `jest-environment-enzyme` where I should to that? Only in each test file?

**Comment by blainekasten** [comment]
Why do you need to import babel polyfill? What are you polyfilling that your native env doesn't support?

**Comment by brneto** [comment]
@blainekasten You right, in fact, I don't need babel polyfill anymore, because `flat-map` and `match-all` was removed from babel polyfill, but I still need import `flat-map` and `match-all` polyfills. So, removing the babel polyfill, that's what I need to from now on using jest-environment-enzyme?
