### ISSUE TITLE
toMatchSelector behaves unexpectedly

### ISSUE THREAD

**Issue by LandonSchropp** [FormidableLabs/enzyme-matchers#253]
I'm trying to match an attribute selector in Jest, but the `toMatchSelector` doesn't seem to be working properly. Here's a simple example:

``` jsx
test("toMatchSelector", () => {
  function Title() {
    return <h1 data-spanish="Hola">Hello</h1>;
  }

  let component = <Title />;

  expect(mount(component)).toMatchSelector("[data-spanish]");
  expect(mount(component)).not.toMatchSelector("[data-french]");
});
```

When running this test, I get the following error:

```
  ✕ toMatchSelector (44ms)

  ● toMatchSelector

    Expected <Title> component to match the selector "[data-spanish]", but it didn't.
    <h1 data-spanish="Hola">Hello</h1>

       6 |   let component = <Title />;
       7 |
    >  8 |   expect(mount(component)).toMatchSelector("[data-spanish]");
         |                            ^
       9 |   expect(mount(component)).not.toMatchSelector("[data-french]");
      10 | });
      11 |

      at Object.toMatchSelector (test/components/shared/to-match-selector.test.jsx:8:28)
```

I can get it to work by calling `find` on the wrapper. However, this is unexpected to me since the `Title` component directly returns the DOM element. Am I missing something in how I understand Enzyme? Or this is a bug?

```
test("toMatchSelector", () => {
  function Title() {
    return <h1 data-spanish="Hola">Hello</h1>;
  }

  let component = <Title />;

  expect(mount(component).find("h1")).toMatchSelector("[data-spanish]");
  expect(mount(component).find("h1")).not.toMatchSelector("[data-french]");
});
```

**Comment by blainekasten** [comment]
This does look peculiar. Make sure you're on the latest versions of my libs and enzyme.

If it is a bug, I believe it'd be on the enzyme side as the `toMatchSelector` api simply calls enzyme's `.is()` api

https://github.com/FormidableLabs/enzyme-matchers/blob/master/packages/enzyme-matchers/src/assertions/toMatchSelector.js#L18

**Comment by blainekasten** [comment]
Gonna close due to lack of response. If you are able to test this and get back to me please do respond though and we can dive into it further.
