### ISSUE TITLE
.toExist() fails to work on a wrapper around a Fragment

### ISSUE THREAD

**Issue by heathzipongo** [FormidableLabs/enzyme-matchers#256]
I have a react component that renders a top-level Fragment.
```
import React, { Fragment } from 'react';

export default function Test() {
  return (
   <Fragment>
    <div>1</div>
    <div>2</div>
   </Fragment>
  );
}
```

When I shallow render the component and check `.toExist()` on the wrapper I receive the following error:
```
TypeError: Cannot convert a Symbol value to a string
```

```
describe('test', () => {
  it('was rendered', () => {
    const wrapper = shallow(<Test/>);
    expect(wrapper).toExist();
  }
});
```

**Comment by blainekasten** [comment]
Interesting, but not wholly surprising. Are you interested in contributing a fix potentially?

**Comment by blainekasten** [comment]
I added tests to the code base. This is working fine with updated enzyme and react. Can you make sure you are using latest enzyme and react?
