### ISSUE TITLE
Do I have to explicitly import the TypeScript definitions?

### ISSUE THREAD

**Issue by lostfictions** [FormidableLabs/enzyme-matchers#258]
Hey there -- I noticed the `jest-enzyme` and `jest-environment-enzyme` packages both supply TypeScript definitions for augmenting the Jest matchers and setting up the global namespace, respectively. That's great!

However, I only seem to be able to get them to work if I explicitly include them in my `tsconfig.json` file, like this:
```json
  "include": ["src/**/*", "node_modules/jest-enzyme/lib/index.d.ts"]
```

Is this how I'm supposed to be doing things?

**Comment by blainekasten** [comment]
Unfortunately, I'm not a typescripter. So i'm going to cc some people who have helped get the types in here and maybe they can help!

Calling all typescripters! @vkrol @astorije @cyberhck @pascalduez

**Comment by lostfictions** [comment]
My hunch is that because the types are defined within the package proper rather than published as their own `@types` package, TypeScript doesn't look for them automatically -- so even though they're global augmentations they don't get pulled in unless another piece of code requires them (or they're explicitly included in compilation in `tsconfig.json`, as I did above).

That means that this suggested setup
```json
"jest": {
  "setupTestFrameworkScriptFile": "./node_modules/jest-enzyme/lib/index.js",
```
won't pull them in, unfortunately.

**Comment by cyberhck** [comment]
yes, we also do what @lostfictions mentioned because we have special matchers as well :smile: when we simply do a `import 'jest-enzyme'` it simply works though, I didn't face any problems which was asked. I'll also link @paibamboo and see if I missed something.

**Comment by blainekasten** [comment]
Gonna close this as it seems to be solvable in user land.
