### ISSUE TITLE
Add support for containsMatchingElement

### ISSUE THREAD

**Issue by GreenGremlin** [FormidableLabs/enzyme-matchers#260]
A common use case with Enzyme is to test that a wrapper contains an element that matches an enzyme selector. This can be done manually, using [`containsMatchingElement`](https://airbnb.io/enzyme/docs/api/ShallowWrapper/containsMatchingElement.html), but this does not produce very readable errors.

A matcher should be created that replicates the `containsMatchingElement` behavior.

```js
const container = shallow(<MyContainer />);

expect(container.containsMatchingElement('.item').toBe(true);
```

This produces the error, "Expected false to be true."

Ideally, you'd be able to do this with a matcher.
```js
const container = shallow(<MyContainer />);

expect(container).toContainMatchingElement('.item');
```

This could produce an error like, "Expected <MyContainer /> to contain an element matching '.item'."

Additionally, a similar matcher should also be created to assert `n` matches.

Possible names for the new matchers:
- `toContainMatchingElement(s)`
- `toContainMatchingReactElement(s)` (inline with `toContainReact`)
- `toContainMatch(es)`

### Implementation notes

For the negative match, the `toContainMatchingElement` matcher will either have to use `.find` and validate the length of the result or handle the error produced by `containsMatchingElement` when more than one match is found.

**Comment by GreenGremlin** [comment]
If there is support for this, I can take a stab at the implementation.

**Comment by GreenGremlin** [comment]
Apparently `containsAllMatchingElements` and `containsAnyMatchingElements` expect an array React elements, which would make them more similar to `toContainReact` than `toContainMatchingElement`.

**Comment by GreenGremlin** [comment]
Another use case to consider would be matching a given selector `n` times.

```js
const container = shallow(<MyContainer />);

expect(container.find('.item').length).toBe(4);
```

Which produce the failure, "Expected 1 to be 4."

```js
const container = shallow(<MyContainer />);

expect(container).toContainMatchingElements('.containedItem', {expectedCount: 4});
```

Which could produce a failure like, "Expected <MyContainer /> to contain 4 elements matching selector '.containedItem' but only found 1."

**Comment by GreenGremlin** [comment]
I'd love to contribute on this, but I'd really like to get a :thumbsup: before doing so.

**Comment by blainekasten** [comment]
Honestly, I really love this API. It's sort of what I always wanted. Green light green light! make it happen!

**Comment by GreenGremlin** [comment]
Done #262
