### ISSUE TITLE
Cannot use custom serializer with this library

### ISSUE THREAD

**Issue by jalooc** [FormidableLabs/enzyme-matchers#261]
When trying to use a custom serializer like this:
```
// jest.config.js

module.exports = {
	// ...
	snapshotSerializers: ['./deep-enzyme-to-json-serializer'],
};
```
```
// deep-enzyme-to-json-serializer.js

const { createSerializer } = require('enzyme-to-json');

module.exports = createSerializer({ mode: 'deep' });
```

my wrappers don't get serialized by it, but by the serializer used in `jest-enzyme` instead (probably here: https://github.com/FormidableLabs/enzyme-matchers/blob/master/packages/jest-enzyme/src/index.js#L22). Is it possible to extend `jest-enzyme` so it accepted serialization options (would it be even possible without sacrificing the ability to use the matcher provided by this lib?)? Or maybe use `expect.addSnapshotSerializer(serializer)` only where custom matchers are used?

**Comment by blainekasten** [comment]
Is there any reason you specifically want the deep mode? imo the default behavior is better than the deep or shallow mode.

Because the default behavior is basically the deep mode, with a wrapper of the actual component, which can help for context.

**Comment by jalooc** [comment]
The reason I needed the deep mode was for the serializer to output the rendered html tags of the whole component tree, omitting the implementation details like component names, props etc. that were included in the default mode.

I dealt with in another way: by using `render()` instead of `mount()` (which after all appeared more logical). So what I wrote in the issue is not needed by me in this particular case any more. However, it's still something that could be customizable for sake of giving a developer the choice between shallow and deep rendered snapshots.

**Comment by blainekasten** [comment]
I'm going to close this for now and wait to see if there are more issues like this before investing the work. More options isn't always better imo. So i'd like to strongly consider the tradeoffs and needs before making this change.

**Comment by tannera** [comment]
The possibility to provide custom options would now be useful because the: `{ ignoreDefaultProps: true }` now exists. https://github.com/adriantoine/enzyme-to-json#helper
