### ISSUE TITLE
jest-enzyme specifying bad version for jest-environment-enzyme

### ISSUE THREAD

**Issue by dammo001** [FormidableLabs/enzyme-matchers#269]
jest-enzyme is specifying version `^6.1.1` for jest-environment-enzyme dependency, but https://www.npmjs.com/package/jest-environment-enzyme only has up to `6.1.0`, causing npm install to fail.

**Comment by anied** [comment]
Worth noting that [somebody already made a pull request to resolve this issue](https://github.com/FormidableLabs/enzyme-matchers/pull/270).  Fingers-crossed that that gets merged shortly...

**Comment by blainekasten** [comment]
Well. This is really weird. I don't know yet how this happened. I'll dig in tomorrow.

For now I would pin `"enzyme-matchers": "6.0.5"`

**Comment by blainekasten** [comment]
6.1.1 is now published. Hopefully that fixes things... sorry for the snafu
