### ISSUE TITLE
`toContainReact` fails even though output matches

### ISSUE THREAD

**Issue by Saser** [FormidableLabs/enzyme-matchers#76]
First off: I have tried searching the web to see if this was a common issue, but that does not seem to be the case. I assume this is the repository I should be posting this issue to -- if it is not, feel free to close it (and please direct me to the correct repository).

Now then!

I have written a recursive React component that I am writing tests for. For some reason, it seems that `toContainReact` fails even though the HTML output contains the expected elements.

I created an application that contains a minimum reproduction (at least as minimum as I could find) of this issue: [`Saser/tocontainreact-failing`](https://github.com/Saser/tocontainreact-failing)

When running the test in the above repo, I get the following output:

```
Expected <div> to contain <span>outer<span>inner</span></span> but it was not found.
HTML Output of <div>:
 <div><span>outer<span>inner</span></span></div>
```

Any idea as to what might be wrong?

**Comment by blainekasten** [comment]
it seems like the outputs are actually different? the actual component output seems to be wrapped in an additional div?

**Comment by Saser** [comment]
Hmm, maybe. Perhaps I haven't grokked everything about hos JSX works and how it interacts with these wrappers and test matchers.

Anyhow, I updated the test to not wrap the component in a `<div>` and instead just render it directly: [Saser/tocontainreact-failing @ `1a8ed51`](https://github.com/Saser/tocontainreact-failing/tree/1a8ed518c95e3d40c7c3027e9cdbf9420e09fd45). The test is still failing, with this output:

```
Expected <Item> to contain <span>outer<span>inner</span></span> but it was not found.
HTML Output of <Item>:
 <span>outer<span>inner</span></span>
```

**Comment by Saser** [comment]
Oh, another note: if I "cheat" and just return the expected output directly, the test is passing.

```javascript
const Item = () => <span>outer<span>inner</span></span>;
```

**Comment by blainekasten** [comment]
Apologies, I haven't had time to dig into this. If you want to look into the code and figure out what's happening I would happily accept a PR!

**Comment by blainekasten** [comment]
Dug into this. Pretty sure there isn't an issue here. I tried to look at your repo, but looks like you deleted it. I'm going to close this for now. If you can help me dive into it sometime I'd love to figure out what's going on.
